# Generated by Django 3.2.10 on 2022-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0006_alter_donations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='zip_code',
            field=models.CharField(max_length=5, verbose_name='Podaj kod pocztowy.'),
        ),
    ]
